secrets:
  telegram_bot_token:
    file: ./secrets/telegram_bot_token.txt
  telegram_allowed_chat_ids:
    file: ./secrets/telegram_allowed_chat_ids.txt

services:
  icloudpd:
    image: ghcr.io/laforcem/icloudpd:latest
    command:
      - "--mfa-provider"
      - "webui"
      - "--watch-with-interval"
      - "3600"
      - "--username"
      - "jdoe@icloud.com"
      - "--directory"
      - "/data"
      - "--notification-forwarder"
    volumes:
      - ./data:/data
      - ./config:/home/icloudpd/.pyicloud
    networks:
      - icloudpd-net

  icloudpd-telegram-bot:
    image: ghcr.io/laforcem/icloudpd-telegram-bot:latest
    environment:
      TELEGRAM_BOT_TOKEN_FILE: /run/secrets/telegram_bot_token
      TELEGRAM_ALLOWED_CHAT_IDS_FILE: /run/secrets/telegram_allowed_chat_ids
      ICLOUDPD_BASE_URL: "http://icloudpd:2011"
    secrets:
      - telegram_bot_token
      - telegram_allowed_chat_ids
    networks:
      - icloudpd-net

networks:
  icloudpd-net:
    driver: bridge
