services:
  icloudpd:
    image: ghcr.io/laforcem/icloudpd:latest
    command:
      - "--mfa-provider"
      - "webui"
      - "--watch-with-interval"
      - "3600"
      - "--username"
      - "jdoe@icloud.com"
      - "--directory"
      - "/data"
      - "--notification-script"
      - "/usr/local/bin/notification_script.py"
    volumes:
      - ./data:/data
      - ./config:/home/icloudpd/.pyicloud
    environment:
      TELEGRAM_BOT_NOTIFY_URL: "http://telegram-bot:8090/notify"
    networks:
      - icloudpd-net

  telegram-bot:
    image: ghcr.io/laforcem/icloudpd-telegram-bot:latest
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_ALLOWED_CHAT_IDS: "${TELEGRAM_ALLOWED_CHAT_IDS}"
      ICLOUDPD_BASE_URL: "http://icloudpd:2011"
    networks:
      - icloudpd-net

networks:
  icloudpd-net:
    driver: bridge
